# Generated by Django 3.2.16 on 2022-10-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20221018_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Post')], default=0),
        ),
    ]
