# Generated by Django 3.2.16 on 2022-10-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='title', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
