# Generated by Django 3.2.16 on 2022-10-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
