# Generated by Django 3.2.16 on 2022-10-27 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='last_name',
            new_name='lname',
        ),
    ]
