# Generated by Django 3.2.16 on 2022-10-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20221027_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='lname',
            new_name='last_name',
        ),
    ]
