# Generated by Django 3.2.16 on 2022-10-30 12:46

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20221027_2028'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='booking',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
